### PR TITLE
Minor improvements.

### PR DESCRIPTION
**Pull request by floitsch**
Kebabify the code.
Make the documentation better suited for the toitdoc viewer.
Add GitHub actions.

### CODE REVIEW

**Comment by floitsch** [comment]
If you prefer keeping the constants (`EOL`, `EOF`, ...) and functions (`read-csv-line1`, `read-csv-field`, ...) public, let me know and I will undo the rename.

**Comment by floitsch** [comment]
Note: once this PR is landed, simply creating a new release with GitHub will automatically publish the package (due to the `publish` action).

**Comment by ojmason** [comment]
I have merged it, thanks!

**Comment by floitsch** [comment]
I don't see any GitHub action running, so maybe they are disabled in this repo. You might want to enable them: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository

**Comment by ojmason** [comment]
I think I have enabled them now. Do I then need to publish separately, or just re-release? Sorry, not a github expert!

**Comment by floitsch** [comment]
They will run automatically with new pushes.
I have two more PRs, so they should just start working.

Once they are merged, just make a new release, where you create a new tag `v1.0.1` (for example) as part of the release.
The rest should happen automatically.

**Comment by ojmason** [comment]
Ok, thanks! I’m just out running a sailing regatta, but will deal with that when I’m back at the computer.

**Comment by floitsch** [comment]
No rush!
Enjoy!

**Pull request merged**
